name: etl
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2023.01.10
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.16
  - python-dateutil=2.8.2
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - pip:
      - et-xmlfile==1.1.0
      - numpy==1.21.6
      - openpyxl==3.0.10
      - pandas==1.3.5
      - pytz==2022.2.1
